Issue 0133 create new spyro version were every dependency not pip installable is optional
NDF-Poli-USP/spyro pull request #137
Opened 2024-11-18 13:09 UTC by Olender

### PR Description: Make Non-Pip-Installable Dependencies Optional in spyro and update license information 

**Summary**  
This PR addresses **Issue #133** by modifying the spyro package to make all dependencies that cannot be installed via `pip` optional. This change improves the flexibility of the library, allowing users to install and use spyro even when certain dependencies are unavailable or difficult to set up. It also updates the license from general to the open-source LGPL-v3. The optional dependencies are SeismicMesh and ROL (ROL was already set as optional before). SeismicMesh is pip installable, however some of its dependencies (especially the required version of CGAL) can require sudo access for updates in older ubuntu versions or installation HPC clusters.

**Key Changes**  
- Updated `setup.py`. 
- Modified import statements throughout the codebase to handle missing dependencies.
- Added or updated tests to ensure spyro functions correctly without the optional dependencies, where applicable.  
- Modified license file.

**Impact**  
- Users can install spyro with a minimal setup and only add the dependencies required for their specific use case.  
- Improves portability and ease of installation for users in constrained environments, especially those using Total Energy's HPC infrastructure.  

**Testing**  
- Verified spyro runs successfully without optional dependencies.  
- Manually tested optional features to ensure they work as expected when dependencies are installed.

2024-11-19 21:47 UTC, SouzaEM requested changes

2024-11-19 21:47 UTC, SouzaEM commented on spyro/tools/velocity_smoother.py
> +        plt.savefig(output_filename+".png")
I think you have to call savefig before you call show to avoid saving a blank figure.

2024-11-19 21:47 UTC, SouzaEM commented on test/test_cpw_calc.py
This test will run MLT or spectral methods depending on the environment. In either case, some part of the code will not be tested. I think the test environment should have SeismicMesh installed and run the test for every method that is supported by spyro.

We may also have another environment or mock approach for testing the logic of SeismicMesh availability. However, I guess this is not the scope of this test in particular.

2024-11-19 21:47 UTC, SouzaEM commented on test/test_elastic_local_abc.py
In this case we can try reducing the memory requirements of the test instead of skipping it. For example, we can try increasing "gradient_sampling_frequency". I left a low (and probably inappropriate) value for this field.

2024-11-19 21:47 UTC, SouzaEM commented on test/test_velocity_smoother.py
> +        plt.savefig("nonsmoothedtest.png")
I think the savefig should come before show to avoid saving a blank image.

2024-11-20 13:24 UTC, Olender commented on spyro/tools/velocity_smoother.py
> +        plt.savefig(output_filename+".png")
Good idea. Changed it in the commit

2024-11-20 13:31 UTC, Olender commented on test/test_cpw_calc.py
You are absolutely right about the importance of running the test for both types of 2D elements, especially to ensure comprehensive coverage. The reason I initially tested only one of these was that this particular test takes a significant amount of time to complete in our runner. However, I agree that we should incorporate both and fixed this in the latest commit.

As for testing the logic of `SeismicMesh` availability, I did attempt to implement something using the `unittest` package and mocks, but I encountered some unexpected issues that I couldn't fully resolve at the time. I plan to revisit this. If you have any suggestions or best practices for handling this kind of dependency testing (e.g., using mocks or creating a lightweight testing environment), I would greatly appreciate your input

2024-11-20 13:33 UTC, Olender commented on test/test_velocity_smoother.py
> +        plt.savefig("nonsmoothedtest.png")
Fixed it in the latest commit

2024-11-20 13:43 UTC, Olender commented on test/test_elastic_local_abc.py
This is a good idea. Once the demeter runner finishes the current jobs, I will SSH into it and try out some different sampling values to see if I can reduce memory requirements without compromising the test.

I am working from home because of the holiday. Therefore, I don't want to risk loosing SSH access to my personal workstation in the lab (that only has 16  GB RAM) by accident while testing this. Demeter has significant more RAM (48 GB) and can run this test as is without a problem.

2024-11-20 14:28 UTC, SouzaEM approved these changes

2024-11-20 17:56 UTC, merged